import Link from "next/link";

import { getStaffHomeSummary, getStaffProfileSummary } from "@/lib/staff/portal";

function money(value: number) { return new Intl.NumberFormat("en-IN", { currency: "INR", maximumFractionDigits: 0, style: "currency" }).format(value); }

export default async function StaffHomePage() {
  const [profile, home] = await Promise.all([getStaffProfileSummary(), getStaffHomeSummary()]);
  if (!profile || !home) return null;
  return <div className="space-y-5"><section><p className="text-sm font-medium text-muted">Welcome</p><h1 className="mt-1 text-3xl font-semibold">{profile.name}</h1><p className="mt-2 text-sm text-muted">{profile.designation ?? "Staff"} · {profile.store.name}</p></section><section className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs text-muted">Today sales</p><p className="mt-2 text-xl font-semibold">{home.sales.linkage_verified ? money(home.today_value) : "Verification needed"}</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-xs text-muted">Month sales</p><p className="mt-2 text-xl font-semibold">{home.sales.linkage_verified ? money(home.sales.summary.value) : "Verification needed"}</p></div><Link className="rounded-2xl border border-border bg-card p-4" href="/staff/tasks"><p className="text-xs text-muted">Pending tasks</p><p className="mt-2 text-xl font-semibold">{home.pending_tasks}</p></Link><Link className="rounded-2xl border border-border bg-card p-4" href="/staff/payslips"><p className="text-xs text-muted">Latest payslip</p><p className="mt-2 text-xl font-semibold">{home.latest_payslip_month ? new Date(`${home.latest_payslip_month}T00:00:00`).toLocaleDateString("en-IN", { month: "short", year: "numeric" }) : "Not linked"}</p></Link></section>{!home.sales.linkage_verified ? <div className="rounded-2xl border border-warning/30 bg-warning/5 p-4 text-sm font-semibold text-warning">Sales linkage requires owner verification.</div> : null}<section className="space-y-3"><h2 className="text-xl font-semibold">Important notices</h2>{home.notices.length ? home.notices.map((notice, index) => <div className="rounded-2xl border border-border bg-card p-4" key={`${notice.created_at}-${index}`}><p className="font-semibold">{notice.title}</p>{notice.details ? <p className="mt-2 text-sm leading-6 text-muted">{notice.details}</p> : null}</div>) : <p className="rounded-2xl border border-border bg-card p-4 text-sm text-muted">No current notices.</p>}</section></div>;
}
